import 'package:flutter/material.dart';

Widget surahButton(BuildContext context, String nombor, String surah, String additionalText, Function() onPressed) {
  return GestureDetector(
    onTap: onPressed,
    child: Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Stack(
          alignment: Alignment.center,
          children: [
            Image.asset('assets/images/nomborplace.png', fit: BoxFit.contain, width: MediaQuery.of(context).size.width * 0.15,),
            Text(nombor, style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.black)),
          ],
        ),
        Stack(
          alignment: Alignment.center,
          children: [
            Image.asset('assets/images/surahplace.png', fit: BoxFit.contain, width: MediaQuery.of(context).size.width * 0.7,),
            // If there's additional text, show it below; otherwise center the surah name
            additionalText.isNotEmpty
                ? Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(surah, style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.black)),
                      Text(additionalText, style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: Colors.black)),
                    ],
                  )
                : Text(surah, style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Colors.black)),
          ],
        ),
      ],
    ),
  );
}

Widget buildSearchField(Function(String) onSearch) {
  return Padding(
      padding: const EdgeInsets.symmetric(vertical: 16.0),
      child: TextField(
        decoration: InputDecoration(
          hintText: 'Search Surah...',
          prefixIcon: Icon(Icons.search),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(32.0),
          ),
        ),
        onChanged: (value) {
          onSearch(value);
        },
      ),
    );
}

final List<Map<String, String>> surahList = [
    {'number': '01', 'name': 'Al-Fatihah', 'name_arab': 'الفاتحة'},
    {'number': '02', 'name': 'Al-Baqarah', 'name_arab': 'البقرة'},
    // {'number': '02', 'name': 'Baqarah Juzuk 2', 'name_arab': 'البقرة الجزء الثاني'},
    // {'number': '02', 'name': 'Baqarah Juzuk 3', 'name_arab': 'البقرة الجزء الثالث'},
    {'number': '03', 'name': 'Ali Imran', 'name_arab': 'آل عمران'},
    {'number': '04', 'name': 'An-Nisa', 'name_arab': 'النساء'},
    {'number': '05', 'name': 'Al-Maidah', 'name_arab': 'المائدة'},
    {'number': '06', 'name': 'Al-An’am', 'name_arab': 'الأنعام'},
    {'number': '07', 'name': 'Al-A’raf', 'name_arab': 'الأعراف'},
    {'number': '08', 'name': 'Anfal', 'name_arab': 'الأنفال'},
    {'number': '09', 'name': 'Tawbah', 'name_arab': 'التوبة'},
    {'number': '10', 'name': 'Yunus', 'name_arab': 'يونس'},
    {'number': '11', 'name': 'Hud', 'name_arab': 'هود'},
    {'number': '12', 'name': 'Yusuf', 'name_arab': 'يوسف'},
    {'number': '13', 'name': 'Al-Ra’d', 'name_arab': 'الرعد'},
    {'number': '14', 'name': 'Ibrahim', 'name_arab': 'إبراهيم'},
    {'number': '15', 'name': 'Al-Hijr', 'name_arab': 'الحجر'},
    {'number': '16', 'name': 'An-Nahl', 'name_arab': 'النحل'},
    {'number': '17', 'name': 'Al-Isra’', 'name_arab': 'الإسراء'},
    {'number': '18', 'name': 'Al-Kahfi', 'name_arab': 'الكهف'},
    {'number': '19', 'name': 'Maryam', 'name_arab': 'مريم'},
    {'number': '20', 'name': 'Taha', 'name_arab': 'طه'},
    {'number': '21', 'name': 'Anbiya’', 'name_arab': 'الأنبياء'},
    {'number': '22', 'name': 'Hajj', 'name_arab': 'الحج'},
    {'number': '23', 'name': 'Mukminoon', 'name_arab': 'المؤمنون'},
    {'number': '24', 'name': 'An-Nur', 'name_arab': 'النور'},
    {'number': '25', 'name': 'Furqan', 'name_arab': 'الفرقان'},
    {'number': '26', 'name': 'Shu’araa', 'name_arab': 'الشعراء'},
    {'number': '27', 'name': 'Naml', 'name_arab': 'النمل'},
    {'number': '28', 'name': 'Qasas', 'name_arab': 'القصص'},
    {'number': '29', 'name': 'Ankabut', 'name_arab': 'العنكبوت'},
    {'number': '30', 'name': 'Rum', 'name_arab': 'الروم'},
    {'number': '31', 'name': 'Luqman', 'name_arab': 'لقمان'},
    {'number': '32', 'name': 'Sajdah', 'name_arab': 'السجدة'},
    {'number': '33', 'name': 'Ahzab', 'name_arab': 'الأحزاب'},
    {'number': '34', 'name': 'Saba', 'name_arab': 'سبأ'},
    {'number': '35', 'name': 'Fatir', 'name_arab': 'فاطر'},
    {'number': '36', 'name': 'Yaasin', 'name_arab': 'يس'},
    {'number': '37', 'name': 'Saffat', 'name_arab': 'الصافات'},
    {'number': '38', 'name': 'Sad', 'name_arab': 'ص'},
    {'number': '39', 'name': 'Az Zumar', 'name_arab': 'الزمر'},
    {'number': '40', 'name': 'Ghafir', 'name_arab': 'غافر'},
    {'number': '41', 'name': 'Fussilat', 'name_arab': 'فصلت'},
    {'number': '42', 'name': 'Shura', 'name_arab': 'الشورى'},
    {'number': '43', 'name': 'Zukhruf', 'name_arab': 'الزخرف'},
    {'number': '44', 'name': 'Dukhan', 'name_arab': 'الدخان'},
    {'number': '45', 'name': 'Jathiya', 'name_arab': 'الجاثية'},
    {'number': '46', 'name': 'Al-Ahqaf', 'name_arab': 'الأحقاف'},
    {'number': '47', 'name': 'Muhammad', 'name_arab': 'محمد'},
    {'number': '48', 'name': 'Al-Fath', 'name_arab': 'الفتح'},
    {'number': '49', 'name': 'Al-Hujurat', 'name_arab': 'الحجرات'},
    {'number': '50', 'name': 'Qaf', 'name_arab': 'ق'},
    {'number': '51', 'name': 'Dhariyat', 'name_arab': 'الذاريات'},
    {'number': '52', 'name': 'Thur', 'name_arab': 'الطور'},
    {'number': '53', 'name': 'Najm', 'name_arab': 'النجم'},
    {'number': '54', 'name': 'Qamar', 'name_arab': 'القمر'},
    {'number': '55', 'name': 'Rahman', 'name_arab': 'الرحمن'},
    {'number': '56', 'name': 'Waqiah', 'name_arab': 'الواقعة'},
    {'number': '57', 'name': 'Hadid', 'name_arab': 'الحديد'},
    {'number': '58', 'name': 'Mujaadilah', 'name_arab': 'المجادلة'},
    {'number': '59', 'name': 'Hashr', 'name_arab': 'الحشر'},
    {'number': '60', 'name': 'Mumtahanah', 'name_arab': 'الممتحنة'},
    {'number': '61', 'name': 'Saff', 'name_arab': 'الصف'},
    {'number': '62', 'name': 'Jumuah', 'name_arab': 'الجمعة'},
    {'number': '63', 'name': 'Munafiqoon', 'name_arab': 'المنافقون'},
    {'number': '64', 'name': 'Taghabun', 'name_arab': 'التغابن'},
    {'number': '65', 'name': 'Talaq', 'name_arab': 'الطلاق'},
    {'number': '66', 'name': 'Tahreem', 'name_arab': 'التحريم'},
    {'number': '67', 'name': 'Mulk', 'name_arab': 'الملك'},
    {'number': '68', 'name': 'Qalam', 'name_arab': 'القلم'},
    {'number': '69', 'name': 'Haqqah', 'name_arab': 'الحاقة'},
    {'number': '70', 'name': 'Maarij', 'name_arab': 'المعارج'},
    {'number': '71', 'name': 'Nuh', 'name_arab': 'نوح'},
    {'number': '72', 'name': 'Jin', 'name_arab': 'الجن'},
    {'number': '73', 'name': 'Muzzammil', 'name_arab': 'المزمل'},
    {'number': '74', 'name': 'Muddaththir', 'name_arab': 'المدثر'},
    {'number': '75', 'name': 'Qiyama', 'name_arab': 'القيامة'},
    {'number': '76', 'name': 'Insan', 'name_arab': 'الإنسان'},
    {'number': '77', 'name': 'Mursalat', 'name_arab': 'المرسلات'},
    {'number': '78', 'name': 'An-Naba’', 'name_arab': 'النبأ'},
    {'number': '79', 'name': 'An-Naaziat', 'name_arab': 'النازعات'},
    {'number': '80', 'name': 'Abasa', 'name_arab': 'عبس'},
    {'number': '81', 'name': 'Takweer', 'name_arab': 'التكوير'},
    {'number': '82', 'name': 'Al-Infithar', 'name_arab': 'الإنفطار'},
    {'number': '83', 'name': 'Mutaffifin', 'name_arab': 'المطففين'},
    {'number': '84', 'name': 'Insyiqaq', 'name_arab': 'الإنشقاق'},
    {'number': '85', 'name': 'Burooj', 'name_arab': 'البروج'},
    {'number': '86', 'name': 'At-Tariq', 'name_arab': 'الطارق'},
    {'number': '87', 'name': 'Al-A’la', 'name_arab': 'الأعلى'},
    {'number': '88', 'name': 'Al-Ghasyihah', 'name_arab': 'الغاشية'},
    {'number': '89', 'name': 'Al-Fajr', 'name_arab': 'الفجر'},
    {'number': '90', 'name': 'Al-Balad', 'name_arab': 'البلد'},
    {'number': '91', 'name': 'Ash-Syams', 'name_arab': 'الشمس'},
    {'number': '92', 'name': 'Al-Layl', 'name_arab': 'الليل'},
    {'number': '93', 'name': 'Dhuha', 'name_arab': 'الضحى'},
    {'number': '94', 'name': 'Al-Sharh', 'name_arab': 'الشرح'},
    {'number': '95', 'name': 'At-Teen', 'name_arab': 'التين'},
    {'number': '96', 'name': 'Al-Alaq', 'name_arab': 'العلق'},
    {'number': '97', 'name': 'Al-Qadr', 'name_arab': 'القدر'},
    {'number': '98', 'name': 'Al-Bayyinah', 'name_arab': 'البينة'},
    {'number': '99', 'name': 'Az-Zalzalah', 'name_arab': 'الزلزلة'},
    {'number': '100', 'name': 'Al-Aadiyat', 'name_arab': 'العاديات'},
    {'number': '101', 'name': 'Al-Qaari’ah', 'name_arab': 'القارعة'},
    {'number': '102', 'name': 'At-Takathur', 'name_arab': 'التكاثر'},
    {'number': '103', 'name': 'Al-Asr', 'name_arab': 'العصر'},
    {'number': '104', 'name': 'Al-Humazah', 'name_arab': 'الهمزة'},
    {'number': '105', 'name': 'Al-Feel', 'name_arab': 'الفيل'},
    {'number': '106', 'name': 'Quraish', 'name_arab': 'قريش'},
    {'number': '107', 'name': 'Al-Ma’un', 'name_arab': 'الماعون'},
    {'number': '108', 'name': 'Al-Kawthar', 'name_arab': 'الكوثر'},
    {'number': '109', 'name': 'Al-Kaafiroon', 'name_arab': 'الكافرون'},
    {'number': '110', 'name': 'An-Nasr', 'name_arab': 'النصر'},
    {'number': '111', 'name': 'Al-Masad', 'name_arab': 'المسد'},
    {'number': '112', 'name': 'Al-Ikhlas', 'name_arab': 'الإخلاص'},
    {'number': '113', 'name': 'Al-Falaq', 'name_arab': 'الفلق'},
    {'number': '114', 'name': 'An-Nas', 'name_arab': 'الناس'},
  ];