name: Build Android APK

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - build-apk  # Triggers on push to build-apk branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Get Dependencies
        run: flutter pub get

      - name: Generate Gradle Wrapper
        run: cd android && gradle wrapper --gradle-version 8.10.2

      - name: Grant Execute Permission for Gradle Wrapper
        run: chmod +x android/gradlew

      - name: Clean Project
        run: cd android && ./gradlew clean

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
